default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV.fetch("POSTGRES_HOST") { "localhost" } %>
  username: <%= ENV.fetch("POSTGRES_USER") { "local_user" } %>
  password: <%= ENV.fetch("POSTGRES_PASSWORD") { "local_password" } %>

development:
  <<: *default
  database: real_state_development

test:
  <<: *default
  database: real_state_test

production:
  <<: *default
  database: real_state_production
  username: real_state
  password: <%= ENV["POSTGRES_PASSWORD"] %>
